### ISSUE TITLE
.Where().Where()

### ISSUE THREAD

**Issue by maleet** [SanderSade/common-linq-mistakes#1]
If I know that provider knows how to combine multiple Where-s then multiple Where-s improve readability quite a lot.

Long non readable && || combination can be really pain to read.

**Comment by SanderSade** [comment]
That is why I write longer predicates like this (which you should know :P):
```
.Where(x =>
    x.Something == otherThing
    && x.OneMore == oneMore
    || x.EvenMore == evenMore)
.ToArray();
```
