### ISSUE TITLE
Few comments

### ISSUE THREAD

**Issue by abatishchev** [SanderSade/common-linq-mistakes#2]
Hi,
Nice write-up! However, few comments:

> Common LINQ mistakes

Reads more like Common LINQ to Entitles mistakes. Most explanations dive into resulting SQL issues. But also there are LINQ to Objects, to XML, other IQueryable implementations, to Cosmos DB, etc. which or might not have these issues, or might have different ones.

>Single() methods go over all elements of the set

- Goes or will go :)
- Concerns only `Single(predicate)`
- `Single()` on all platforms basically will make just 2 iterations instead of 1. If logically or semantically there should be only a single element, it's fine to use it because the penalty is insignificant.

>I am not sure why people just select the items 

- Usually a left over after refactoring, indeed.
- Or to return `IEnumerable` instead of a concrete class, probably. There is special method `ToEnumerable()` but this is still a common mistake.

**Comment by oriash93** [comment]
You have a typo. It's `ToEnumerable()`.

**Comment by abatishchev** [comment]
Right, thanks! Fixed.

**Comment by SanderSade** [comment]
Yes - I definitely made a mistake, and should have been much clearer that this applies to all LINQ providers, and SQL is there just to clarify the logic. This short list is aimed at people new to LINQ, and I figured they probably are at least somewhat familiar with SQL already.

Good points regarding Single() and Select() - thank you. 

I hope to do some updates within a week or so, and I'll try to clarify/include all of these. If you don't mind, I'll ping you in this thread for a review?

**Comment by abatishchev** [comment]
Sure, would be happy to help.

**Comment by SanderSade** [comment]
@abatishchev Do you think the changes (see PR) fix this issue?

**Comment by SanderSade** [comment]
PR merged, going to close this. Please keep the comments and suggestions coming!
