### ISSUE TITLE
Suggestion: Regular Expressions to find mistakes

### ISSUE THREAD

**Issue by oriash93** [SanderSade/common-linq-mistakes#3]
Hey,

First let me say, your article and explanations are great.
As a developer working with legacy code and old conventions/standards, I come across these mistakes daily.

I want to suggest some tips on finding these mistakes, using regular expressions:

## .Single() and .SingleOrDefault()
use: `\.Single(OrDefault)?\(.*\)`

## .First() and .FirstOrDefault()  
use: `\.First(OrDefault)?\(.*\)`

## Empty .Count()
use: `\.Count\(\)`

## Other occurences of .Count()
use: `\.Count\(.*\)`
or in this case `if.*\(.*\.Count\(.*\)\)` might help.

## .Where().First() and .Where().FirstOrDefault()
use: `\.Where\(.*\)\.First(OrDefault)?\(.*\)`

## .Where().Where()
use: `\.Where\(.*\)\.Where\(.*\)`

## .OrderBy().OrderBy()
use: `\.OrderBy\(.*\)\.OrderBy\(.*\)`

## .Select(x => x)
use: `\.Select\((\w)\s*=>\s*\1\)`

**Comment by aaronmorgan** [comment]
Suggested amendment to .Where().First()

## .Where().First...()
use: `\.Where\(.*\)\.First.*\(.*\)`

**Comment by SanderSade** [comment]
I am not sure how to include these, as I don't want to overload the main article - the intended audience are newcomers to LINQ, and regexes might be too intimidating for them? Perhaps a separate MD file, linked from the readme.md?

**Comment by oriash93** [comment]
@aaronmorgan you're right, I fixed it.

@SanderSade I think your idea is better. Up to you :)

**Comment by SanderSade** [comment]
@oriash93 Do you think this format works - see the PR?

**Comment by oriash93** [comment]
@SanderSade  Yes. I approve 👍

**Comment by SanderSade** [comment]
Thank you - going to close this issue, but please do keep suggestions and comments coming!
